### ISSUE TITLE
Data element too large

### ISSUE THREAD

**Issue by dennychou63** [seryal/OPCComponent#1]
My environment is as follows:
FPC 3.2.0
win10

The following error occurred during component installation:
Compile package syopcpack 0.0: Exit code 1, Errors: 2

OPCtypes.pas(39,69) Error: Data element too large

OPCtypes.pas(53,68) Error: Data element too large

How can I solve this problem? thanks

**Comment by seryal** [comment]
Hello.

Do you compile for 32 or 64 bits?

**Comment by dennychou63** [comment]
32 bits

**Comment by seryal** [comment]
Try it now

**Comment by dennychou63** [comment]
I have tested it and the above problem has been solved. thank you very much
